name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build
      - name: Upload to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ secrets.BUILD_PATH }}/
          server-dir: ${{ secrets.FTP_PATH }}/
